version: '1.0'

services:
  taxes-db:
    image: mysql:8.0.27
    restart: always
    ports:
      - 9800:3306
    expose:
      - 3306
    volumes:
      - taxes-db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: 'exercicedb'
      MYSQL_ROOT_PASSWORD: 'root'

volumes:
  taxes-db: